In [ ]:
import numpy as np

In [ ]:
# 2-D Array
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

In [ ]:
arr2d1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

In [ ]:
# 3-D Array
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10, 11, 12]
                  ]
])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.size

12

# Numpy Operations

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
120 * np.ones((2, 3))

array([[120., 120., 120.],
       [120., 120., 120.]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Random
np.random.randn(2, 3)

array([[-0.25198797, -0.48570475,  1.7501288 ],
       [-0.38420202, -0.02573511, -1.53913192]])

In [ ]:
np.random.rand(2, 3)

array([[0.7700619 , 0.01501112, 0.31069964],
       [0.65819792, 0.36494583, 0.38860409]])

In [ ]:
np.random.randint(0, 100, (2, 3))

array([[44, 74,  1],
       [79, 79, 75]])

In [ ]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
str_arr = np.array(['1.1', '2.2', '3.3', '4.4'])

In [ ]:
str_arr

array(['1.1', '2.2', '3.3', '4.4'], dtype='<U3')

In [ ]:
# conversion
arr = np.array(str_arr, dtype='float')

In [ ]:
arr

array([1.1, 2.2, 3.3, 4.4])

In [ ]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [ ]:
arr1

array([[0.82422385, 0.93483572, 0.79701028, 0.14170743],
       [0.07512377, 0.20938486, 0.04459219, 0.96589319],
       [0.33941788, 0.63733952, 0.59196467, 0.29909964]])

In [ ]:
arr2

array([[0.30576318, 0.48275884, 0.18611652, 0.03557415],
       [0.61112147, 0.2308147 , 0.46850394, 0.0230344 ],
       [0.10681434, 0.27289186, 0.44526877, 0.94980912]])

In [ ]:
arr1 + arr2

array([[1.12998702, 1.41759456, 0.98312679, 0.17728157],
       [0.68624524, 0.44019956, 0.51309613, 0.98892759],
       [0.44623222, 0.91023138, 1.03723344, 1.24890877]])

In [ ]:
arr1 - arr2

array([[ 0.51846067,  0.45207688,  0.61089376,  0.10613328],
       [-0.53599769, -0.02142983, -0.42391175,  0.94285879],
       [ 0.23260354,  0.36444765,  0.1466959 , -0.65070948]])

In [ ]:
arr1 * arr2

array([[0.2520173 , 0.45130021, 0.14833678, 0.00504112],
       [0.04590975, 0.0483291 , 0.02089162, 0.02224877],
       [0.0362547 , 0.17392477, 0.26358338, 0.28408757]])

In [ ]:
arr1 / arr2

array([[ 2.69562819,  1.93644454,  4.28231889,  3.98343868],
       [ 0.12292773,  0.90715568,  0.09517997, 41.93263445],
       [ 3.17764338,  2.33550209,  1.32945471,  0.314905  ]])

In [ ]:
np.exp(arr1)

array([[2.28011036, 2.54679504, 2.21889711, 1.15223949],
       [1.07801757, 1.23291941, 1.04560137, 2.62713313],
       [1.40412998, 1.89144203, 1.80753614, 1.348644  ]])

In [ ]:
np.log(arr1)

array([[-0.19331313, -0.06738446, -0.22688771, -1.95399071],
       [-2.58861822, -1.56358127, -3.11019653, -0.03470202],
       [-1.08052324, -0.45045277, -0.52430833, -1.2069785 ]])

In [ ]:
np.log(np.exp(arr1))

array([[0.82422385, 0.93483572, 0.79701028, 0.14170743],
       [0.07512377, 0.20938486, 0.04459219, 0.96589319],
       [0.33941788, 0.63733952, 0.59196467, 0.29909964]])

In [ ]:
np.sqrt(arr1)

array([[0.90786775, 0.96686903, 0.89275432, 0.37644047],
       [0.27408716, 0.45758591, 0.21116863, 0.98279865],
       [0.58259581, 0.79833547, 0.7693924 , 0.54690003]])

In [ ]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


### Question 1: Find the mean, median for Sachin, Rahul, India

In [ ]:
cric_data = np.loadtxt("cric_data.tsv")

ValueError: ignored

In [ ]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)

In [ ]:
cric_data.shape

(225, 4)

In [ ]:
cric_data = cric_data[:, [1, 2, 3]]

In [ ]:
cric_data.shape

(225, 3)

In [ ]:
sachin = cric_data[:, 0]
rahul = cric_data[:, 1]
india = cric_data[:, 2]

In [ ]:
sachin.shape

(225,)

In [ ]:
def stats(col):
  print('Mean', np.mean(col))
  print('Median', np.median(col))

In [ ]:
stats(sachin)

Mean 39.87555555555556
Median 27.0


In [ ]:
stats(rahul)

Mean 32.062222222222225
Median 22.0


In [ ]:
stats(india)

Mean 220.79555555555555
Median 216.0


In [ ]:
np.mean(cric_data, axis=0)

array([ 39.87555556,  32.06222222, 220.79555556])

### Question 2: Find histogram of Sachin's scores with 10 bins

In [ ]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

### Question 3: find mean of sachin's scores grouped by 25 matches

In [ ]:
sachin.shape

(225,)

In [ ]:
sachin25 = sachin.reshape(9, 25)

In [ ]:
sachin25.shape

(9, 25)

In [ ]:
np.mean(sachin25, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

### Question 4: Find mean of Sachin's scores where he has scored a century


In [ ]:
sachin >= 100

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
sachin[sachin >= 100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])

In [ ]:
np.mean(sachin[sachin >= 100])

125.0

### Question 5: Find mean of Sachin's scores when Rahul has scored less than 10

In [ ]:
rahul <= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True, False,  True, False,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False, False, False,
        True,  True,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
        True, False,

In [ ]:
sachin[rahul <= 10]

array([ 37.,  14.,   4.,   0.,  62.,  38.,  65.,   0.,  48.,  62.,  27.,
        27.,  51.,  18.,  65.,  28.,   2.,  54.,   4.,  14., 100.,  57.,
         0.,   5.,   0.,  30.,  83.,  93.,   0., 152.,   0.,   1.,  53.,
         0.,  81.,  78., 122.,   9.,  13.,  36.,  29.,  12.,  34., 100.,
        44.,  82.,   0.,   6.,  49.,  64.,  43.,  72.,   3.,  44.,  47.,
        17.,  35.,  88.,   0.,  33., 110., 146.,   7.,  11.,  94.,  55.,
         0.,  28.,   2.,  27.,  40.])

In [ ]:
np.mean(sachin[rahul <= 10])

40.2112676056338