### **NIFTY case study**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
nifty = pd.read_csv("NIFTY.csv",index_col=0).iloc[:,0]

In [ ]:
nifty

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 245, dtype: float64

In [ ]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

In [ ]:
nifty.head(10)

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
09-Jan-2019    10855.15
10-Jan-2019    10821.60
11-Jan-2019    10794.95
14-Jan-2019    10737.60
Name: Close, dtype: float64

In [ ]:
nifty.tail()

Date
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [ ]:
nifty.tail(10)

Date
17-Dec-2019    12165.00
18-Dec-2019    12221.65
19-Dec-2019    12259.70
20-Dec-2019    12271.80
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [ ]:
np.mean(nifty)

11432.632244897959

In [ ]:
type(nifty)

pandas.core.series.Series

In [ ]:
np.median(nifty)

11512.4

###Question: How many days did the markets close higher than the previous day's close?

In [ ]:
nifty.iloc[0]

10910.1

In [ ]:
nifty[0]

10910.1

In [ ]:
nifty[1]

10792.5

In [ ]:
nifty[1]-nifty[0]

-117.60000000000036

In [ ]:
nifty[1:]

Date
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 244, dtype: float64

In [ ]:
nifty[:-1]

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
Name: Close, Length: 244, dtype: float64

In [ ]:
nifty[1:]-nifty[:-1]

Date
01-Apr-2019    0.0
01-Aug-2019    0.0
01-Feb-2019    0.0
01-Jan-2019    NaN
01-Jul-2019    0.0
              ... 
31-Dec-2019    NaN
31-Jan-2019    0.0
31-Jul-2019    0.0
31-May-2019    0.0
31-Oct-2019    0.0
Name: Close, Length: 245, dtype: float64

In [ ]:
nifty.values[1:] - nifty.values[:-1]

array([-1.1760e+02, -1.2025e+02,  5.5100e+01,  4.4450e+01,  3.0350e+01,
        5.3000e+01, -3.3550e+01, -2.6650e+01, -5.7350e+01,  1.4920e+02,
        3.5000e+00,  1.4900e+01,  1.7500e+00,  5.4900e+01, -3.9100e+01,
       -9.1250e+01,  1.8300e+01, -6.9250e+01, -1.1900e+02, -9.3500e+00,
       -4.0000e-01,  1.7915e+02,  6.2700e+01,  1.8600e+01,  2.2100e+01,
        1.2810e+02,  6.9500e+00, -1.2580e+02, -5.4800e+01, -5.7400e+01,
       -3.7750e+01, -4.7600e+01, -2.1650e+01, -8.3450e+01, -3.6600e+01,
        1.3110e+02,  5.4400e+01,  1.8000e+00,  8.8450e+01, -4.4800e+01,
       -2.8650e+01, -1.4150e+01,  7.1000e+01,  1.2395e+02,  6.5550e+01,
        5.2000e+00, -2.2800e+01,  1.3265e+02,  1.3315e+02,  4.0500e+01,
        1.5500e+00,  8.3600e+01,  3.5350e+01,  7.0200e+01, -1.1350e+01,
       -6.4150e+01, -1.0265e+02,  1.2900e+02, -3.8200e+01,  1.2495e+02,
        5.3900e+01,  4.5250e+01,  4.4050e+01, -6.9250e+01, -4.5950e+01,
        6.7950e+01, -6.1450e+01,  6.7450e+01, -8.7650e+01,  1.24

In [ ]:
(nifty.values[1:] - nifty.values[:-1]) > 0

array([False, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False, False,

In [ ]:
np.sum((nifty.values[1:] - nifty.values[:-1]) > 0)

129

### **DATAFRAMES:**

In [ ]:
arr = np.random.randint(0,10,(5,3))

In [ ]:
arr

array([[1, 4, 6],
       [4, 9, 7],
       [5, 8, 5],
       [1, 0, 4],
       [3, 3, 0]])

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0  1  2
0  1  4  6
1  4  9  7
2  5  8  5
3  1  0  4
4  3  3  0

In [ ]:
df.values

array([[1, 4, 6],
       [4, 9, 7],
       [5, 8, 5],
       [1, 0, 4],
       [3, 3, 0]])

In [ ]:
df.index  #Rows

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns  #columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
for c in df.columns:
  print(c)

0
1
2


In [ ]:
df.values[0]

array([1, 4, 6])

In [ ]:
df.values[1]

array([4, 9, 7])

In [ ]:
# renaming (row labelling)
df.index = ["R1","R2","R3","R4","R5"]
df.columns = ["C1","C2","C3"] #Column labelling

In [ ]:
df

C1  C2  C3
R1   1   4   6
R2   4   9   7
R3   5   8   5
R4   1   0   4
R5   3   3   0

In [ ]:
df.loc["R3"]

C1    5
C2    8
C3    5
Name: R3, dtype: int64

In [ ]:
df.loc["R3","C2"]

8

In [ ]:
df.iloc[2,1]

8

In [ ]:
temp_df = df.iloc[2:4,1:3] #slicing dataframe

In [ ]:
temp_df

C2  C3
R3   8   5
R4   0   4

In [ ]:
type(temp_df)

pandas.core.frame.DataFrame

In [ ]:
# dataframe is collection of series

df.iloc[0]    # Across column

C1    1
C2    4
C3    6
Name: R1, dtype: int64

In [ ]:
type(df.iloc[0])

pandas.core.series.Series

In [ ]:
df.iloc[:,0]    # across row

R1    1
R2    4
R3    5
R4    1
R5    3
Name: C1, dtype: int64